POST http://localhost:5001/api/insert
Content-Type: application/json

{"id":"be3b24c2-f01e-4816-945f-567f1ccb6acf","event-type":"TRACE_EVENT","occurredOn":"2021-03-14T22:22:59.205261","version":1,"graph-id":"file-states","nature":"raw-file","object-name":"File-25","path":"[TO_BE_PURGED, PURGED]"}

###

GET http://localhost:5001/api/all
Content-Type: application/json

###
GET http://localhost:5001/api/mongo/path?object-name=File-24
Content-Type: application/json

### 
GET http://localhost:5001/api/stats